version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - bash build.sh install
  build:
    commands:
      - echo Build started on `date`
      - bash build.sh build $STAGE $REGION
  post_build:
    commands:
      - bash build.sh deploy $STAGE
artifacts:
  files:
    - '**/*'
  base-directory: build